---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "pipeline-pychopper"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "Workspaces"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-pychopper"

## Pipeline-specific parameters:

# Directory with fastq files
fastq_dir: "/nfs/groups_ech/apps/active/bsipos/data/sirv_e0_1d2_fl"

# cDNA primers
primers: ">cDNA|1\nTTTCTGTTGGTGCTGATATTGCTGGG\n>cDNA|2\nAAAAGAAGATAGAGCGACAGGCAAGT"

# Alignment parameters (match,mismatch,gap_open,gap_extend)
aln_params: "1,-1,2,1"

# Number of bases to scan at each end
target_length: 200

# Number of samples when calculating score cutoff
sample_size: 100000

# Score cutoff percentile
score_percentile: 98

# Use more sensitive (and error prone) heuristic mode
heu_mode: "true"

# Stringency in heuristic mode
heu_stringency: 0.15
